services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  debian_python:
    build:
      context: ./debian
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./debian/scripts:/home/desafio_python/scripts
      - ./debian/data_files:/home/desafio_python/data_files 
    working_dir: /home/desafio_python
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    command: bash -c "sh /home/desafio_python/scripts/pipeline.sh && tail -f /dev/null"

volumes:
  pgdata:
